#!/usr/bin/env python3
from __future__ import annotations
import csv
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "DATA_MANIFEST.md"

def sniff_header(path: Path) -> str:
    suffix = path.suffix.lower()
    try:
        if suffix in {".csv", ".tsv"}:
            delim = "\t" if suffix == ".tsv" else ","
            with path.open(newline="", encoding="utf-8", errors="replace") as f:
                row = next(csv.reader(f, delimiter=delim))
            return " | ".join(row[:40])
        if suffix in {".xlsx", ".xlsm"}:
            import openpyxl
            wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
            ws = wb[wb.sheetnames[0]]
            row = next(ws.iter_rows(max_row=1, values_only=True))
            wb.close()
            return " | ".join("" if c is None else str(c) for c in row[:40])
        if suffix in {".json", ".geojson"}:
            return path.read_text(encoding="utf-8", errors="replace").replace("\n", " ")[:240]
        if suffix in {".shp", ".gpkg", ".tif", ".tiff"}:
            return "binary " + suffix
    except Exception as exc:
        return "(could not sniff: %s)" % exc
    return ""

def main() -> None:
    rows = []
    if RAW.exists():
        for p in sorted(RAW.rglob("*")):
            if not p.is_file() or p.name == ".gitkeep":
                continue
            rows.append((p.relative_to(ROOT).as_posix(), p.stat().st_size, p.suffix.lower(), sniff_header(p)))
    lines = [
        "# DATA_MANIFEST",
        "",
        "Generated by scripts/inventory_raw.py.",
        "",
        "| path | bytes | suffix | header_or_preview |",
        "|---|---:|---|---|",
    ]
    for path, nbytes, suffix, preview in rows:
        preview = preview.replace("|", "\\|").replace("\n", " ")
        lines.append("| `%s` | %s | %s | %s |" % (path, nbytes, suffix, preview))
    if not rows:
        lines.append("| _(nothing in data/raw yet)_ | | | |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote %s (%s files)" % (OUT, len(rows)))

if __name__ == "__main__":
    main()
